apiVersion: v1
description: Unbound is a fast caching DNS resolver
home: https://www.unbound.net/
name: unbound
version: 0.0.3
appVersion: 0.0.1
sources:
- http://unbound.nlnetlabs.nl/svn/
- https://github.com/kubernetes/contrib/tree/master/exec-healthz
maintainers:
- name: Tomas Hulata
  email: thulata@pixelfederation.com
