apiVersion: v1
description: Unbound is a fast caching DNS resolver
home: https://www.unbound.net/
name: unbound
version: 0.0.6
appVersion: 0.0.1
sources:
- https://github.com/brdelphus/unbound/
- http://unbound.nlnetlabs.nl/svn/
- https://github.com/kubernetes/contrib/tree/master/exec-healthz
maintainers:
- name: Rodrigo Graeff
  email: delphus@delphus.org
